(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function auth(){return window.CAPTAUP_AUTH}
function isCeo(){const u=window.__captaupUser;return !!u&&String(u.accessRole||'').toLowerCase()==='ceo'}
function css(){if($('adm-access-css'))return;const s=document.createElement('style');s.id='adm-access-css';s.textContent=`#captaupAdmBtn{border:1px solid #25597b;background:#0b2130;color:#86cfff;border-radius:999px;padding:7px 10px;font-size:8px;font-weight:950;cursor:pointer}.adm-overlay{position:fixed;inset:0;z-index:100002;background:#02070dea;display:grid;place-items:center;padding:16px}.adm-box{width:min(700px,100%);max-height:88vh;overflow:auto;background:#07131f;border:1px solid #23577a;border-radius:20px;padding:18px;color:#eaf7ff;box-shadow:0 24px 80px #000b}.adm-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.adm-title{font-size:19px;font-weight:950}.adm-sub{font-size:9px;color:#7f9bb0;margin-top:3px}.adm-close{border:0;border-radius:8px;background:#102536;color:#a9cbe0;padding:8px 10px;font-size:8px;font-weight:900;cursor:pointer}.adm-list{display:grid;gap:9px;margin-top:14px}.adm-item{border:1px solid #1a3c55;border-radius:12px;background:#081823;padding:11px}.adm-item b{display:block;font-size:11px;word-break:break-all}.adm-item small{display:block;color:#7692a6;font-size:8px;margin-top:3px}.adm-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.adm-actions button{border:0;border-radius:8px;padding:8px 10px;color:white;font-size:8px;font-weight:950;cursor:pointer}.adm-active{background:#1b9a62}.adm-life{background:#385fd1}.adm-off{background:#a63b45}.adm-empty{padding:20px;text-align:center;color:#7894a8;font-size:9px}.adm-error{margin-top:12px;padding:10px;border:1px solid #6e3540;border-radius:10px;color:#ffb6bd;background:#231015;font-size:9px}`;document.head.appendChild(s)}
async function loadUsers(){const a=auth();if(!a?.apiFetch)throw new Error('AUREON Base indisponível');return a.apiFetch(`/admin/projects/${a.projectSlug}/users`)}
async function updateAccess(userId,status,role='member'){const a=auth();await a.apiFetch(`/admin/projects/${a.projectSlug}/users/${encodeURIComponent(userId)}/access`,{method:'PUT',body:JSON.stringify({status,role})});await render()}
async function render(){const root=$('captaupAdmPanel');if(!root)return;root.innerHTML=`<div class="adm-box"><div class="adm-head"><div><div class="adm-title">ADM • Acessos</div><div class="adm-sub">Acessos oficiais validados pela AUREON Base.</div></div><button class="adm-close" id="admClose">FECHAR</button></div><div id="admContent"><div class="adm-empty">Carregando usuários...</div></div></div>`;$('admClose').onclick=()=>root.remove();const content=$('admContent');try{const users=await loadUsers();content.innerHTML=`<div class="adm-list">${users.length?users.map(u=>`<div class="adm-item"><b>${esc(u.email)}</b><small>Status: ${esc(u.status||'sem assinatura')} • Papel: ${esc(u.role||'member')} • ${u.access?.allowed?'ACESSO LIBERADO':'ACESSO BLOQUEADO'}</small><div class="adm-actions"><button class="adm-active" data-id="${esc(u.id)}" data-status="active" data-role="${esc(u.role||'member')}">ATIVAR</button><button class="adm-life" data-id="${esc(u.id)}" data-status="lifetime" data-role="${esc(u.role||'member')}">VITALÍCIO</button><button class="adm-off" data-id="${esc(u.id)}" data-status="inactive" data-role="${esc(u.role||'member')}">BLOQUEAR</button></div></div>`).join(''):'<div class="adm-empty">Nenhum usuário vinculado ao CAPTAUP.</div>'}</div>`;content.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await updateAccess(b.dataset.id,b.dataset.status,b.dataset.role)}catch(e){b.disabled=false;alert('Não foi possível atualizar o acesso agora.')}})}catch(e){content.innerHTML=`<div class="adm-error">Não foi possível carregar os acessos pela AUREON Base. Confirme que o projeto “captaup” existe e que seu usuário é superadministrador.</div>`}}
function open(){if(!isCeo())return;let root=$('captaupAdmPanel');if(root)root.remove();root=document.createElement('div');root.id='captaupAdmPanel';root.className='adm-overlay';document.body.appendChild(root);render()}
function mount(){css();if(!isCeo())return;const chip=$('captaupUserChip');if(!chip){setTimeout(mount,150);return}if(!$('captaupAdmBtn')){const b=document.createElement('button');b.id='captaupAdmBtn';b.textContent='ADM';b.onclick=open;chip.insertBefore(b,chip.lastElementChild)}}
window.addEventListener('captaup-auth-changed',()=>setTimeout(mount,50));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
})();
