(function(){
'use strict';
const API='https://aureonbase.vercel.app';
const PROJECT='captaup';
const SESSION_KEY='captaup_aureon_session_v1';
const PROFILE_KEY='captaup_user_profile_v2';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').trim().toLowerCase();
function readSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function saveSession(v){sessionStorage.setItem(SESSION_KEY,JSON.stringify(v))}
function clearSession(){sessionStorage.removeItem(SESSION_KEY);localStorage.removeItem(PROFILE_KEY);delete window.__captaupUser}
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const r=await fetch(API+path,{...options,headers,cache:'no-store',credentials:'omit',redirect:'error'});let data=null;const type=r.headers.get('content-type')||'';if(type.includes('application/json')){try{data=await r.json()}catch{}}if(!r.ok){const e=new Error(data?.error||`http_${r.status}`);e.status=r.status;e.data=data;throw e}return data}
async function refresh(){const s=readSession();if(!s?.refresh_token)return false;try{const data=await request('/auth/refresh',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});saveSession({...s,access_token:data.access_token});return true}catch{clearSession();return false}}
async function apiFetch(path,options={}){let s=readSession();if(!s?.access_token)throw new Error('not_authenticated');const run=()=>request(path,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${readSession()?.access_token||''}`}});try{return await run()}catch(e){if(e.status!==401||!(await refresh()))throw e;return run()}}
function profileFrom(me,access){const role=me?.is_superadmin||access?.project?.role==='owner'?'CEO':'Profissional';const name=(me?.email||'Usuário').split('@')[0].replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());return{email:me.email,name,accessRole:role,performanceRole:'promotor',at:Date.now(),source:'aureon-base'}}
function publishProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p));window.__captaupUser=p;window.dispatchEvent(new CustomEvent('captaup-auth-changed',{detail:p}))}
function initials(name){return String(name||'CU').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function css(){if($('captaup-auth-css'))return;const s=document.createElement('style');s.id='captaup-auth-css';s.textContent=`#captaupAuth{position:fixed;inset:0;z-index:100000;background:radial-gradient(circle at 50% 15%,#0d2740 0,#07111b 38%,#02070d 100%);display:grid;place-items:center;padding:20px;font-family:inherit;color:#eaf7ff}.ca-box{width:min(440px,100%);border:1px solid #1c4e72;border-radius:22px;background:linear-gradient(155deg,#091724,#06101a);box-shadow:0 34px 90px #000c,0 0 70px #138cf522;padding:26px}.ca-logo{display:flex;align-items:center;gap:12px;margin-bottom:20px}.ca-mark{width:46px;height:46px;border-radius:14px;background:linear-gradient(135deg,#1683ff,#5f4dff);display:grid;place-items:center;font-size:24px;font-weight:950}.ca-brand{font-weight:950;font-size:20px}.ca-brand small{display:block;font-size:8px;letter-spacing:2px;color:#7696ae}.ca-title{font-size:22px;font-weight:950;margin:8px 0 5px}.ca-sub{font-size:10px;line-height:1.5;color:#86a0b4;margin-bottom:18px}.ca-field{margin-top:10px}.ca-field label{display:block;font-size:8px;color:#7893a7;margin:0 0 6px;letter-spacing:1px}.ca-field input{width:100%;box-sizing:border-box;border-radius:12px;border:1px solid #23465e;background:#05101a;color:#f5fbff;padding:13px 14px}.ca-btn{width:100%;margin-top:14px;border:0;border-radius:12px;padding:13px;background:linear-gradient(135deg,#1683ff,#3f6bff);color:#fff;font-weight:950;cursor:pointer}.ca-link{width:100%;margin-top:10px;border:0;background:transparent;color:#78bfff;font-size:9px;cursor:pointer}.ca-msg{min-height:16px;margin-top:10px;color:#ffb27a;font-size:9px}.ca-safe{margin-top:14px;padding:10px;border:1px solid #183a51;border-radius:10px;background:#071521;color:#6f8da2;font-size:8px;line-height:1.5}.ca-user{display:flex;align-items:center;gap:8px;margin-left:auto;padding:6px 8px;border:1px solid #1d4d6f;background:#071724;border-radius:999px}.ca-avatar{width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#1683ff,#6d4cff);display:grid;place-items:center;font-size:10px;font-weight:950}.ca-meta{font-size:8px;line-height:1.2;color:#88a2b6}.ca-meta b{display:block;color:#eaf7ff;font-size:9px;max-width:160px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ca-logout{border:0;background:transparent;color:#7ba8c5;font-size:8px;cursor:pointer}@media(max-width:700px){.ca-meta{display:none}}`;document.head.appendChild(s)}
function renderUserChip(user){const top=document.querySelector('.top');if(!top)return;let chip=$('captaupUserChip');if(!chip){chip=document.createElement('div');chip.id='captaupUserChip';top.appendChild(chip)}chip.className='ca-user';chip.innerHTML=`<div class="ca-avatar">${esc(initials(user.name))}</div><div class="ca-meta"><b>${esc(user.name)}</b>${esc(user.accessRole)}</div><button class="ca-logout" id="captaupLogout">SAIR</button>`;$('captaupLogout').onclick=logout}
function showLogin(message=''){let root=$('captaupAuth');if(root)root.remove();root=document.createElement('div');root.id='captaupAuth';root.innerHTML=`<div class="ca-box"><div class="ca-logo"><div class="ca-mark">C</div><div class="ca-brand">CAPTAUP<small>ACESSO SEGURO • AUREON BASE</small></div></div><div class="ca-title">Entrar na operação</div><div class="ca-sub">Use seu e-mail e senha da AUREON Base.</div><div class="ca-field"><label>E-MAIL</label><input id="caEmail" type="email" autocomplete="username" inputmode="email"></div><div class="ca-field"><label>SENHA</label><input id="caPassword" type="password" autocomplete="current-password"></div><button class="ca-btn" id="caContinue">ENTRAR</button><button class="ca-link" id="caForgot">Esqueci minha senha</button><div class="ca-msg" id="caMsg">${esc(message)}</div><div class="ca-safe">A autenticação é validada no servidor. Tokens ficam apenas nesta sessão do navegador e respostas de autenticação não são lidas do cache.</div></div>`;document.body.appendChild(root);$('caContinue').onclick=login;$('caPassword').onkeydown=e=>{if(e.key==='Enter')login()};$('caForgot').onclick=requestReset;$('caEmail').focus()}
async function login(){const email=norm($('caEmail')?.value),password=String($('caPassword')?.value||''),msg=$('caMsg');if(!email||!password){msg.textContent='Informe e-mail e senha.';return}msg.textContent='Validando acesso...';try{const tokens=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})});saveSession({access_token:tokens.access_token,refresh_token:tokens.refresh_token});const me=await apiFetch('/me');let access=null;try{access=await apiFetch(`/projects/${PROJECT}/access`)}catch(e){if(!me.is_superadmin)throw e}if(!me.is_superadmin&&access?.access?.allowed!==true)throw new Error('subscription_required');const p=profileFrom(me,access);publishProfile(p);$('captaupAuth')?.remove();renderUserChip(p)}catch(e){clearSession();msg.textContent=e.message==='subscription_required'||e.message==='project_forbidden'?'Seu usuário existe, mas não possui acesso ativo ao CAPTAUP.':'E-mail ou senha inválidos, ou serviço indisponível.'}}
async function requestReset(){const email=norm($('caEmail')?.value),msg=$('caMsg');if(!email){msg.textContent='Digite seu e-mail primeiro.';return}try{await request('/auth/request-password-reset',{method:'POST',body:JSON.stringify({email})});msg.textContent='Se o e-mail estiver cadastrado, as instruções de recuperação serão enviadas.'}catch{msg.textContent='Não foi possível solicitar a recuperação agora.'}}
async function logout(){const s=readSession();try{if(s?.access_token)await apiFetch('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token||''})})}catch{}clearSession();location.reload()}
async function restore(){const s=readSession();if(!s?.access_token)return false;try{const me=await apiFetch('/me');let access=null;try{access=await apiFetch(`/projects/${PROJECT}/access`)}catch(e){if(!me.is_superadmin)throw e}if(!me.is_superadmin&&access?.access?.allowed!==true)throw new Error('no_access');const p=profileFrom(me,access);publishProfile(p);renderUserChip(p);return true}catch{clearSession();return false}}
async function boot(){css();if(!(await restore()))showLogin()}
window.CAPTAUP_AUTH={apiBase:API,projectSlug:PROJECT,apiFetch,readSession,logout};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
